/*
Navicat MySQL Data Transfer

Source Server         : Local
Source Server Version : 50612
Source Host           : localhost:3306
Source Database       : lessonscast

Target Server Type    : MYSQL
Target Server Version : 50612
File Encoding         : 65001

Date: 2014-07-20 19:46:01
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for falists
-- ----------------------------
DROP TABLE IF EXISTS `falists`;
CREATE TABLE `falists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `faicons` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=530 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of falists
-- ----------------------------
INSERT INTO `falists` VALUES ('1', 'fa-lg\r');
INSERT INTO `falists` VALUES ('2', 'fa-2x\r');
INSERT INTO `falists` VALUES ('3', 'fa-3x\r');
INSERT INTO `falists` VALUES ('4', 'fa-4x\r');
INSERT INTO `falists` VALUES ('5', 'fa-5x\r');
INSERT INTO `falists` VALUES ('6', 'fa-fw \r');
INSERT INTO `falists` VALUES ('7', 'fa-ul \r');
INSERT INTO `falists` VALUES ('8', 'fa-li \r');
INSERT INTO `falists` VALUES ('9', 'fa-lifa-lg \r');
INSERT INTO `falists` VALUES ('10', 'fa-border \r');
INSERT INTO `falists` VALUES ('11', 'pull-right \r');
INSERT INTO `falists` VALUES ('12', 'pull-left \r');
INSERT INTO `falists` VALUES ('13', 'fapull-left \r');
INSERT INTO `falists` VALUES ('14', 'fapull-right \r');
INSERT INTO `falists` VALUES ('15', 'fa-spin \r');
INSERT INTO `falists` VALUES ('16', 'fa-rotate-90 \r');
INSERT INTO `falists` VALUES ('17', 'fa-rotate-180 \r');
INSERT INTO `falists` VALUES ('18', 'fa-rotate-270 \r');
INSERT INTO `falists` VALUES ('19', 'fa-flip-horizontal \r');
INSERT INTO `falists` VALUES ('20', 'fa-flip-vertical \r');
INSERT INTO `falists` VALUES ('21', 'fa-stack \r');
INSERT INTO `falists` VALUES ('22', 'fa-stack-1x\r');
INSERT INTO `falists` VALUES ('23', 'fa-stack-2x \r');
INSERT INTO `falists` VALUES ('24', 'fa-stack-1x \r');
INSERT INTO `falists` VALUES ('25', 'fa-stack-2x \r');
INSERT INTO `falists` VALUES ('26', 'fa-inverse \r');
INSERT INTO `falists` VALUES ('27', 'fa-glass \r');
INSERT INTO `falists` VALUES ('28', 'fa-music \r');
INSERT INTO `falists` VALUES ('29', 'fa-search \r');
INSERT INTO `falists` VALUES ('30', 'fa-envelope-o \r');
INSERT INTO `falists` VALUES ('31', 'fa-heart \r');
INSERT INTO `falists` VALUES ('32', 'fa-star \r');
INSERT INTO `falists` VALUES ('33', 'fa-star-o \r');
INSERT INTO `falists` VALUES ('34', 'fa-user \r');
INSERT INTO `falists` VALUES ('35', 'fa-film \r');
INSERT INTO `falists` VALUES ('36', 'fa-th-large \r');
INSERT INTO `falists` VALUES ('37', 'fa-th \r');
INSERT INTO `falists` VALUES ('38', 'fa-th-list \r');
INSERT INTO `falists` VALUES ('39', 'fa-check \r');
INSERT INTO `falists` VALUES ('40', 'fa-times \r');
INSERT INTO `falists` VALUES ('41', 'fa-search-plus \r');
INSERT INTO `falists` VALUES ('42', 'fa-search-minus \r');
INSERT INTO `falists` VALUES ('43', 'fa-power-off \r');
INSERT INTO `falists` VALUES ('44', 'fa-signal \r');
INSERT INTO `falists` VALUES ('45', 'fa-gear\r');
INSERT INTO `falists` VALUES ('46', 'fa-cog \r');
INSERT INTO `falists` VALUES ('47', 'fa-trash-o \r');
INSERT INTO `falists` VALUES ('48', 'fa-home \r');
INSERT INTO `falists` VALUES ('49', 'fa-file-o \r');
INSERT INTO `falists` VALUES ('50', 'fa-clock-o \r');
INSERT INTO `falists` VALUES ('51', 'fa-road \r');
INSERT INTO `falists` VALUES ('52', 'fa-download \r');
INSERT INTO `falists` VALUES ('53', 'fa-arrow-circle-o-down \r');
INSERT INTO `falists` VALUES ('54', 'fa-arrow-circle-o-up \r');
INSERT INTO `falists` VALUES ('55', 'fa-inbox \r');
INSERT INTO `falists` VALUES ('56', 'fa-play-circle-o \r');
INSERT INTO `falists` VALUES ('57', 'fa-rotate-right\r');
INSERT INTO `falists` VALUES ('58', 'fa-repeat \r');
INSERT INTO `falists` VALUES ('59', 'fa-refresh \r');
INSERT INTO `falists` VALUES ('60', 'fa-list-alt \r');
INSERT INTO `falists` VALUES ('61', 'fa-lock \r');
INSERT INTO `falists` VALUES ('62', 'fa-flag \r');
INSERT INTO `falists` VALUES ('63', 'fa-headphones \r');
INSERT INTO `falists` VALUES ('64', 'fa-volume-off \r');
INSERT INTO `falists` VALUES ('65', 'fa-volume-down \r');
INSERT INTO `falists` VALUES ('66', 'fa-volume-up \r');
INSERT INTO `falists` VALUES ('67', 'fa-qrcode \r');
INSERT INTO `falists` VALUES ('68', 'fa-barcode \r');
INSERT INTO `falists` VALUES ('69', 'fa-tag \r');
INSERT INTO `falists` VALUES ('70', 'fa-tags \r');
INSERT INTO `falists` VALUES ('71', 'fa-book \r');
INSERT INTO `falists` VALUES ('72', 'fa-bookmark \r');
INSERT INTO `falists` VALUES ('73', 'fa-print \r');
INSERT INTO `falists` VALUES ('74', 'fa-camera \r');
INSERT INTO `falists` VALUES ('75', 'fa-font \r');
INSERT INTO `falists` VALUES ('76', 'fa-bold \r');
INSERT INTO `falists` VALUES ('77', 'fa-italic \r');
INSERT INTO `falists` VALUES ('78', 'fa-text-height \r');
INSERT INTO `falists` VALUES ('79', 'fa-text-width \r');
INSERT INTO `falists` VALUES ('80', 'fa-align-left \r');
INSERT INTO `falists` VALUES ('81', 'fa-align-center \r');
INSERT INTO `falists` VALUES ('82', 'fa-align-right \r');
INSERT INTO `falists` VALUES ('83', 'fa-align-justify \r');
INSERT INTO `falists` VALUES ('84', 'fa-list \r');
INSERT INTO `falists` VALUES ('85', 'fa-dedent\r');
INSERT INTO `falists` VALUES ('86', 'fa-outdent \r');
INSERT INTO `falists` VALUES ('87', 'fa-indent \r');
INSERT INTO `falists` VALUES ('88', 'fa-video-camera \r');
INSERT INTO `falists` VALUES ('89', 'fa-photo\r');
INSERT INTO `falists` VALUES ('90', 'fa-image\r');
INSERT INTO `falists` VALUES ('91', 'fa-picture-o \r');
INSERT INTO `falists` VALUES ('92', 'fa-pencil \r');
INSERT INTO `falists` VALUES ('93', 'fa-map-marker \r');
INSERT INTO `falists` VALUES ('94', 'fa-adjust \r');
INSERT INTO `falists` VALUES ('95', 'fa-tint \r');
INSERT INTO `falists` VALUES ('96', 'fa-edit\r');
INSERT INTO `falists` VALUES ('97', 'fa-pencil-square-o \r');
INSERT INTO `falists` VALUES ('98', 'fa-share-square-o \r');
INSERT INTO `falists` VALUES ('99', 'fa-check-square-o \r');
INSERT INTO `falists` VALUES ('100', 'fa-arrows \r');
INSERT INTO `falists` VALUES ('101', 'fa-step-backward \r');
INSERT INTO `falists` VALUES ('102', 'fa-fast-backward \r');
INSERT INTO `falists` VALUES ('103', 'fa-backward \r');
INSERT INTO `falists` VALUES ('104', 'fa-play \r');
INSERT INTO `falists` VALUES ('105', 'fa-pause \r');
INSERT INTO `falists` VALUES ('106', 'fa-stop \r');
INSERT INTO `falists` VALUES ('107', 'fa-forward \r');
INSERT INTO `falists` VALUES ('108', 'fa-fast-forward \r');
INSERT INTO `falists` VALUES ('109', 'fa-step-forward \r');
INSERT INTO `falists` VALUES ('110', 'fa-eject \r');
INSERT INTO `falists` VALUES ('111', 'fa-chevron-left \r');
INSERT INTO `falists` VALUES ('112', 'fa-chevron-right \r');
INSERT INTO `falists` VALUES ('113', 'fa-plus-circle \r');
INSERT INTO `falists` VALUES ('114', 'fa-minus-circle \r');
INSERT INTO `falists` VALUES ('115', 'fa-times-circle \r');
INSERT INTO `falists` VALUES ('116', 'fa-check-circle \r');
INSERT INTO `falists` VALUES ('117', 'fa-question-circle \r');
INSERT INTO `falists` VALUES ('118', 'fa-info-circle \r');
INSERT INTO `falists` VALUES ('119', 'fa-crosshairs \r');
INSERT INTO `falists` VALUES ('120', 'fa-times-circle-o \r');
INSERT INTO `falists` VALUES ('121', 'fa-check-circle-o \r');
INSERT INTO `falists` VALUES ('122', 'fa-ban \r');
INSERT INTO `falists` VALUES ('123', 'fa-arrow-left \r');
INSERT INTO `falists` VALUES ('124', 'fa-arrow-right \r');
INSERT INTO `falists` VALUES ('125', 'fa-arrow-up \r');
INSERT INTO `falists` VALUES ('126', 'fa-arrow-down \r');
INSERT INTO `falists` VALUES ('127', 'fa-mail-forward\r');
INSERT INTO `falists` VALUES ('128', 'fa-share \r');
INSERT INTO `falists` VALUES ('129', 'fa-expand \r');
INSERT INTO `falists` VALUES ('130', 'fa-compress \r');
INSERT INTO `falists` VALUES ('131', 'fa-plus \r');
INSERT INTO `falists` VALUES ('132', 'fa-minus \r');
INSERT INTO `falists` VALUES ('133', 'fa-asterisk \r');
INSERT INTO `falists` VALUES ('134', 'fa-exclamation-circle \r');
INSERT INTO `falists` VALUES ('135', 'fa-gift \r');
INSERT INTO `falists` VALUES ('136', 'fa-leaf \r');
INSERT INTO `falists` VALUES ('137', 'fa-fire \r');
INSERT INTO `falists` VALUES ('138', 'fa-eye \r');
INSERT INTO `falists` VALUES ('139', 'fa-eye-slash \r');
INSERT INTO `falists` VALUES ('140', 'fa-warning\r');
INSERT INTO `falists` VALUES ('141', 'fa-exclamation-triangle \r');
INSERT INTO `falists` VALUES ('142', 'fa-plane \r');
INSERT INTO `falists` VALUES ('143', 'fa-calendar \r');
INSERT INTO `falists` VALUES ('144', 'fa-random \r');
INSERT INTO `falists` VALUES ('145', 'fa-comment \r');
INSERT INTO `falists` VALUES ('146', 'fa-magnet \r');
INSERT INTO `falists` VALUES ('147', 'fa-chevron-up \r');
INSERT INTO `falists` VALUES ('148', 'fa-chevron-down \r');
INSERT INTO `falists` VALUES ('149', 'fa-retweet \r');
INSERT INTO `falists` VALUES ('150', 'fa-shopping-cart \r');
INSERT INTO `falists` VALUES ('151', 'fa-folder \r');
INSERT INTO `falists` VALUES ('152', 'fa-folder-open \r');
INSERT INTO `falists` VALUES ('153', 'fa-arrows-v \r');
INSERT INTO `falists` VALUES ('154', 'fa-arrows-h \r');
INSERT INTO `falists` VALUES ('155', 'fa-bar-chart-o \r');
INSERT INTO `falists` VALUES ('156', 'fa-twitter-square \r');
INSERT INTO `falists` VALUES ('157', 'fa-facebook-square \r');
INSERT INTO `falists` VALUES ('158', 'fa-camera-retro \r');
INSERT INTO `falists` VALUES ('159', 'fa-key \r');
INSERT INTO `falists` VALUES ('160', 'fa-gears\r');
INSERT INTO `falists` VALUES ('161', 'fa-cogs \r');
INSERT INTO `falists` VALUES ('162', 'fa-comments \r');
INSERT INTO `falists` VALUES ('163', 'fa-thumbs-o-up \r');
INSERT INTO `falists` VALUES ('164', 'fa-thumbs-o-down \r');
INSERT INTO `falists` VALUES ('165', 'fa-star-half \r');
INSERT INTO `falists` VALUES ('166', 'fa-heart-o \r');
INSERT INTO `falists` VALUES ('167', 'fa-sign-out \r');
INSERT INTO `falists` VALUES ('168', 'fa-linkedin-square \r');
INSERT INTO `falists` VALUES ('169', 'fa-thumb-tack \r');
INSERT INTO `falists` VALUES ('170', 'fa-external-link \r');
INSERT INTO `falists` VALUES ('171', 'fa-sign-in \r');
INSERT INTO `falists` VALUES ('172', 'fa-trophy \r');
INSERT INTO `falists` VALUES ('173', 'fa-github-square \r');
INSERT INTO `falists` VALUES ('174', 'fa-upload \r');
INSERT INTO `falists` VALUES ('175', 'fa-lemon-o \r');
INSERT INTO `falists` VALUES ('176', 'fa-phone \r');
INSERT INTO `falists` VALUES ('177', 'fa-square-o \r');
INSERT INTO `falists` VALUES ('178', 'fa-bookmark-o \r');
INSERT INTO `falists` VALUES ('179', 'fa-phone-square \r');
INSERT INTO `falists` VALUES ('180', 'fa-twitter \r');
INSERT INTO `falists` VALUES ('181', 'fa-facebook \r');
INSERT INTO `falists` VALUES ('182', 'fa-github \r');
INSERT INTO `falists` VALUES ('183', 'fa-unlock \r');
INSERT INTO `falists` VALUES ('184', 'fa-credit-card \r');
INSERT INTO `falists` VALUES ('185', 'fa-rss \r');
INSERT INTO `falists` VALUES ('186', 'fa-hdd-o \r');
INSERT INTO `falists` VALUES ('187', 'fa-bullhorn \r');
INSERT INTO `falists` VALUES ('188', 'fa-bell \r');
INSERT INTO `falists` VALUES ('189', 'fa-certificate \r');
INSERT INTO `falists` VALUES ('190', 'fa-hand-o-right \r');
INSERT INTO `falists` VALUES ('191', 'fa-hand-o-left \r');
INSERT INTO `falists` VALUES ('192', 'fa-hand-o-up \r');
INSERT INTO `falists` VALUES ('193', 'fa-hand-o-down \r');
INSERT INTO `falists` VALUES ('194', 'fa-arrow-circle-left \r');
INSERT INTO `falists` VALUES ('195', 'fa-arrow-circle-right \r');
INSERT INTO `falists` VALUES ('196', 'fa-arrow-circle-up \r');
INSERT INTO `falists` VALUES ('197', 'fa-arrow-circle-down \r');
INSERT INTO `falists` VALUES ('198', 'fa-globe \r');
INSERT INTO `falists` VALUES ('199', 'fa-wrench \r');
INSERT INTO `falists` VALUES ('200', 'fa-tasks \r');
INSERT INTO `falists` VALUES ('201', 'fa-filter \r');
INSERT INTO `falists` VALUES ('202', 'fa-briefcase \r');
INSERT INTO `falists` VALUES ('203', 'fa-arrows-alt \r');
INSERT INTO `falists` VALUES ('204', 'fa-group\r');
INSERT INTO `falists` VALUES ('205', 'fa-users \r');
INSERT INTO `falists` VALUES ('206', 'fa-chain\r');
INSERT INTO `falists` VALUES ('207', 'fa-link \r');
INSERT INTO `falists` VALUES ('208', 'fa-cloud \r');
INSERT INTO `falists` VALUES ('209', 'fa-flask \r');
INSERT INTO `falists` VALUES ('210', 'fa-cut\r');
INSERT INTO `falists` VALUES ('211', 'fa-scissors \r');
INSERT INTO `falists` VALUES ('212', 'fa-copy\r');
INSERT INTO `falists` VALUES ('213', 'fa-files-o \r');
INSERT INTO `falists` VALUES ('214', 'fa-paperclip \r');
INSERT INTO `falists` VALUES ('215', 'fa-save\r');
INSERT INTO `falists` VALUES ('216', 'fa-floppy-o \r');
INSERT INTO `falists` VALUES ('217', 'fa-square \r');
INSERT INTO `falists` VALUES ('218', 'fa-navicon\r');
INSERT INTO `falists` VALUES ('219', 'fa-reorder\r');
INSERT INTO `falists` VALUES ('220', 'fa-bars \r');
INSERT INTO `falists` VALUES ('221', 'fa-list-ul \r');
INSERT INTO `falists` VALUES ('222', 'fa-list-ol \r');
INSERT INTO `falists` VALUES ('223', 'fa-strikethrough \r');
INSERT INTO `falists` VALUES ('224', 'fa-underline \r');
INSERT INTO `falists` VALUES ('225', 'fa-table \r');
INSERT INTO `falists` VALUES ('226', 'fa-magic \r');
INSERT INTO `falists` VALUES ('227', 'fa-truck \r');
INSERT INTO `falists` VALUES ('228', 'fa-pinterest \r');
INSERT INTO `falists` VALUES ('229', 'fa-pinterest-square \r');
INSERT INTO `falists` VALUES ('230', 'fa-google-plus-square \r');
INSERT INTO `falists` VALUES ('231', 'fa-google-plus \r');
INSERT INTO `falists` VALUES ('232', 'fa-money \r');
INSERT INTO `falists` VALUES ('233', 'fa-caret-down \r');
INSERT INTO `falists` VALUES ('234', 'fa-caret-up \r');
INSERT INTO `falists` VALUES ('235', 'fa-caret-left \r');
INSERT INTO `falists` VALUES ('236', 'fa-caret-right \r');
INSERT INTO `falists` VALUES ('237', 'fa-columns \r');
INSERT INTO `falists` VALUES ('238', 'fa-unsorted\r');
INSERT INTO `falists` VALUES ('239', 'fa-sort \r');
INSERT INTO `falists` VALUES ('240', 'fa-sort-down\r');
INSERT INTO `falists` VALUES ('241', 'fa-sort-desc \r');
INSERT INTO `falists` VALUES ('242', 'fa-sort-up\r');
INSERT INTO `falists` VALUES ('243', 'fa-sort-asc \r');
INSERT INTO `falists` VALUES ('244', 'fa-envelope \r');
INSERT INTO `falists` VALUES ('245', 'fa-linkedin \r');
INSERT INTO `falists` VALUES ('246', 'fa-rotate-left\r');
INSERT INTO `falists` VALUES ('247', 'fa-undo \r');
INSERT INTO `falists` VALUES ('248', 'fa-legal\r');
INSERT INTO `falists` VALUES ('249', 'fa-gavel \r');
INSERT INTO `falists` VALUES ('250', 'fa-dashboard\r');
INSERT INTO `falists` VALUES ('251', 'fa-tachometer \r');
INSERT INTO `falists` VALUES ('252', 'fa-comment-o \r');
INSERT INTO `falists` VALUES ('253', 'fa-comments-o \r');
INSERT INTO `falists` VALUES ('254', 'fa-flash\r');
INSERT INTO `falists` VALUES ('255', 'fa-bolt \r');
INSERT INTO `falists` VALUES ('256', 'fa-sitemap \r');
INSERT INTO `falists` VALUES ('257', 'fa-umbrella \r');
INSERT INTO `falists` VALUES ('258', 'fa-paste\r');
INSERT INTO `falists` VALUES ('259', 'fa-clipboard \r');
INSERT INTO `falists` VALUES ('260', 'fa-lightbulb-o \r');
INSERT INTO `falists` VALUES ('261', 'fa-exchange \r');
INSERT INTO `falists` VALUES ('262', 'fa-cloud-download \r');
INSERT INTO `falists` VALUES ('263', 'fa-cloud-upload \r');
INSERT INTO `falists` VALUES ('264', 'fa-user-md \r');
INSERT INTO `falists` VALUES ('265', 'fa-stethoscope \r');
INSERT INTO `falists` VALUES ('266', 'fa-suitcase \r');
INSERT INTO `falists` VALUES ('267', 'fa-bell-o \r');
INSERT INTO `falists` VALUES ('268', 'fa-coffee \r');
INSERT INTO `falists` VALUES ('269', 'fa-cutlery \r');
INSERT INTO `falists` VALUES ('270', 'fa-file-text-o \r');
INSERT INTO `falists` VALUES ('271', 'fa-building-o \r');
INSERT INTO `falists` VALUES ('272', 'fa-hospital-o \r');
INSERT INTO `falists` VALUES ('273', 'fa-ambulance \r');
INSERT INTO `falists` VALUES ('274', 'fa-medkit \r');
INSERT INTO `falists` VALUES ('275', 'fa-fighter-jet \r');
INSERT INTO `falists` VALUES ('276', 'fa-beer \r');
INSERT INTO `falists` VALUES ('277', 'fa-h-square \r');
INSERT INTO `falists` VALUES ('278', 'fa-plus-square \r');
INSERT INTO `falists` VALUES ('279', 'fa-angle-double-left \r');
INSERT INTO `falists` VALUES ('280', 'fa-angle-double-right \r');
INSERT INTO `falists` VALUES ('281', 'fa-angle-double-up \r');
INSERT INTO `falists` VALUES ('282', 'fa-angle-double-down \r');
INSERT INTO `falists` VALUES ('283', 'fa-angle-left \r');
INSERT INTO `falists` VALUES ('284', 'fa-angle-right \r');
INSERT INTO `falists` VALUES ('285', 'fa-angle-up \r');
INSERT INTO `falists` VALUES ('286', 'fa-angle-down \r');
INSERT INTO `falists` VALUES ('287', 'fa-desktop \r');
INSERT INTO `falists` VALUES ('288', 'fa-laptop \r');
INSERT INTO `falists` VALUES ('289', 'fa-tablet \r');
INSERT INTO `falists` VALUES ('290', 'fa-mobile-phone\r');
INSERT INTO `falists` VALUES ('291', 'fa-mobile \r');
INSERT INTO `falists` VALUES ('292', 'fa-circle-o \r');
INSERT INTO `falists` VALUES ('293', 'fa-quote-left \r');
INSERT INTO `falists` VALUES ('294', 'fa-quote-right \r');
INSERT INTO `falists` VALUES ('295', 'fa-spinner \r');
INSERT INTO `falists` VALUES ('296', 'fa-circle \r');
INSERT INTO `falists` VALUES ('297', 'fa-mail-reply\r');
INSERT INTO `falists` VALUES ('298', 'fa-reply \r');
INSERT INTO `falists` VALUES ('299', 'fa-github-alt \r');
INSERT INTO `falists` VALUES ('300', 'fa-folder-o \r');
INSERT INTO `falists` VALUES ('301', 'fa-folder-open-o \r');
INSERT INTO `falists` VALUES ('302', 'fa-smile-o \r');
INSERT INTO `falists` VALUES ('303', 'fa-frown-o \r');
INSERT INTO `falists` VALUES ('304', 'fa-meh-o \r');
INSERT INTO `falists` VALUES ('305', 'fa-gamepad \r');
INSERT INTO `falists` VALUES ('306', 'fa-keyboard-o \r');
INSERT INTO `falists` VALUES ('307', 'fa-flag-o \r');
INSERT INTO `falists` VALUES ('308', 'fa-flag-checkered \r');
INSERT INTO `falists` VALUES ('309', 'fa-terminal \r');
INSERT INTO `falists` VALUES ('310', 'fa-code \r');
INSERT INTO `falists` VALUES ('311', 'fa-mail-reply-all\r');
INSERT INTO `falists` VALUES ('312', 'fa-reply-all \r');
INSERT INTO `falists` VALUES ('313', 'fa-star-half-empty\r');
INSERT INTO `falists` VALUES ('314', 'fa-star-half-full\r');
INSERT INTO `falists` VALUES ('315', 'fa-star-half-o \r');
INSERT INTO `falists` VALUES ('316', 'fa-location-arrow \r');
INSERT INTO `falists` VALUES ('317', 'fa-crop \r');
INSERT INTO `falists` VALUES ('318', 'fa-code-fork \r');
INSERT INTO `falists` VALUES ('319', 'fa-unlink\r');
INSERT INTO `falists` VALUES ('320', 'fa-chain-broken \r');
INSERT INTO `falists` VALUES ('321', 'fa-question \r');
INSERT INTO `falists` VALUES ('322', 'fa-info \r');
INSERT INTO `falists` VALUES ('323', 'fa-exclamation \r');
INSERT INTO `falists` VALUES ('324', 'fa-superscript \r');
INSERT INTO `falists` VALUES ('325', 'fa-subscript \r');
INSERT INTO `falists` VALUES ('326', 'fa-eraser \r');
INSERT INTO `falists` VALUES ('327', 'fa-puzzle-piece \r');
INSERT INTO `falists` VALUES ('328', 'fa-microphone \r');
INSERT INTO `falists` VALUES ('329', 'fa-microphone-slash \r');
INSERT INTO `falists` VALUES ('330', 'fa-shield \r');
INSERT INTO `falists` VALUES ('331', 'fa-calendar-o \r');
INSERT INTO `falists` VALUES ('332', 'fa-fire-extinguisher \r');
INSERT INTO `falists` VALUES ('333', 'fa-rocket \r');
INSERT INTO `falists` VALUES ('334', 'fa-maxcdn \r');
INSERT INTO `falists` VALUES ('335', 'fa-chevron-circle-left \r');
INSERT INTO `falists` VALUES ('336', 'fa-chevron-circle-right \r');
INSERT INTO `falists` VALUES ('337', 'fa-chevron-circle-up \r');
INSERT INTO `falists` VALUES ('338', 'fa-chevron-circle-down \r');
INSERT INTO `falists` VALUES ('339', 'fa-html5 \r');
INSERT INTO `falists` VALUES ('340', 'fa-css3 \r');
INSERT INTO `falists` VALUES ('341', 'fa-anchor \r');
INSERT INTO `falists` VALUES ('342', 'fa-unlock-alt \r');
INSERT INTO `falists` VALUES ('343', 'fa-bullseye \r');
INSERT INTO `falists` VALUES ('344', 'fa-ellipsis-h \r');
INSERT INTO `falists` VALUES ('345', 'fa-ellipsis-v \r');
INSERT INTO `falists` VALUES ('346', 'fa-rss-square \r');
INSERT INTO `falists` VALUES ('347', 'fa-play-circle \r');
INSERT INTO `falists` VALUES ('348', 'fa-ticket \r');
INSERT INTO `falists` VALUES ('349', 'fa-minus-square \r');
INSERT INTO `falists` VALUES ('350', 'fa-minus-square-o \r');
INSERT INTO `falists` VALUES ('351', 'fa-level-up \r');
INSERT INTO `falists` VALUES ('352', 'fa-level-down \r');
INSERT INTO `falists` VALUES ('353', 'fa-check-square \r');
INSERT INTO `falists` VALUES ('354', 'fa-pencil-square \r');
INSERT INTO `falists` VALUES ('355', 'fa-external-link-square \r');
INSERT INTO `falists` VALUES ('356', 'fa-share-square \r');
INSERT INTO `falists` VALUES ('357', 'fa-compass \r');
INSERT INTO `falists` VALUES ('358', 'fa-toggle-down\r');
INSERT INTO `falists` VALUES ('359', 'fa-caret-square-o-down \r');
INSERT INTO `falists` VALUES ('360', 'fa-toggle-up\r');
INSERT INTO `falists` VALUES ('361', 'fa-caret-square-o-up \r');
INSERT INTO `falists` VALUES ('362', 'fa-toggle-right\r');
INSERT INTO `falists` VALUES ('363', 'fa-caret-square-o-right \r');
INSERT INTO `falists` VALUES ('364', 'fa-euro\r');
INSERT INTO `falists` VALUES ('365', 'fa-eur \r');
INSERT INTO `falists` VALUES ('366', 'fa-gbp \r');
INSERT INTO `falists` VALUES ('367', 'fa-dollar\r');
INSERT INTO `falists` VALUES ('368', 'fa-usd \r');
INSERT INTO `falists` VALUES ('369', 'fa-rupee\r');
INSERT INTO `falists` VALUES ('370', 'fa-inr \r');
INSERT INTO `falists` VALUES ('371', 'fa-cny\r');
INSERT INTO `falists` VALUES ('372', 'fa-rmb\r');
INSERT INTO `falists` VALUES ('373', 'fa-yen\r');
INSERT INTO `falists` VALUES ('374', 'fa-jpy \r');
INSERT INTO `falists` VALUES ('375', 'fa-ruble\r');
INSERT INTO `falists` VALUES ('376', 'fa-rouble\r');
INSERT INTO `falists` VALUES ('377', 'fa-rub \r');
INSERT INTO `falists` VALUES ('378', 'fa-won\r');
INSERT INTO `falists` VALUES ('379', 'fa-krw \r');
INSERT INTO `falists` VALUES ('380', 'fa-bitcoin\r');
INSERT INTO `falists` VALUES ('381', 'fa-btc \r');
INSERT INTO `falists` VALUES ('382', 'fa-file \r');
INSERT INTO `falists` VALUES ('383', 'fa-file-text \r');
INSERT INTO `falists` VALUES ('384', 'fa-sort-alpha-asc \r');
INSERT INTO `falists` VALUES ('385', 'fa-sort-alpha-desc \r');
INSERT INTO `falists` VALUES ('386', 'fa-sort-amount-asc \r');
INSERT INTO `falists` VALUES ('387', 'fa-sort-amount-desc \r');
INSERT INTO `falists` VALUES ('388', 'fa-sort-numeric-asc \r');
INSERT INTO `falists` VALUES ('389', 'fa-sort-numeric-desc \r');
INSERT INTO `falists` VALUES ('390', 'fa-thumbs-up \r');
INSERT INTO `falists` VALUES ('391', 'fa-thumbs-down \r');
INSERT INTO `falists` VALUES ('392', 'fa-youtube-square \r');
INSERT INTO `falists` VALUES ('393', 'fa-youtube \r');
INSERT INTO `falists` VALUES ('394', 'fa-xing \r');
INSERT INTO `falists` VALUES ('395', 'fa-xing-square \r');
INSERT INTO `falists` VALUES ('396', 'fa-youtube-play \r');
INSERT INTO `falists` VALUES ('397', 'fa-dropbox \r');
INSERT INTO `falists` VALUES ('398', 'fa-stack-overflow \r');
INSERT INTO `falists` VALUES ('399', 'fa-instagram \r');
INSERT INTO `falists` VALUES ('400', 'fa-flickr \r');
INSERT INTO `falists` VALUES ('401', 'fa-adn \r');
INSERT INTO `falists` VALUES ('402', 'fa-bitbucket \r');
INSERT INTO `falists` VALUES ('403', 'fa-bitbucket-square \r');
INSERT INTO `falists` VALUES ('404', 'fa-tumblr \r');
INSERT INTO `falists` VALUES ('405', 'fa-tumblr-square \r');
INSERT INTO `falists` VALUES ('406', 'fa-long-arrow-down \r');
INSERT INTO `falists` VALUES ('407', 'fa-long-arrow-up \r');
INSERT INTO `falists` VALUES ('408', 'fa-long-arrow-left \r');
INSERT INTO `falists` VALUES ('409', 'fa-long-arrow-right \r');
INSERT INTO `falists` VALUES ('410', 'fa-apple \r');
INSERT INTO `falists` VALUES ('411', 'fa-windows \r');
INSERT INTO `falists` VALUES ('412', 'fa-android \r');
INSERT INTO `falists` VALUES ('413', 'fa-linux \r');
INSERT INTO `falists` VALUES ('414', 'fa-dribbble \r');
INSERT INTO `falists` VALUES ('415', 'fa-skype \r');
INSERT INTO `falists` VALUES ('416', 'fa-foursquare \r');
INSERT INTO `falists` VALUES ('417', 'fa-trello \r');
INSERT INTO `falists` VALUES ('418', 'fa-female \r');
INSERT INTO `falists` VALUES ('419', 'fa-male \r');
INSERT INTO `falists` VALUES ('420', 'fa-gittip \r');
INSERT INTO `falists` VALUES ('421', 'fa-sun-o \r');
INSERT INTO `falists` VALUES ('422', 'fa-moon-o \r');
INSERT INTO `falists` VALUES ('423', 'fa-archive \r');
INSERT INTO `falists` VALUES ('424', 'fa-bug \r');
INSERT INTO `falists` VALUES ('425', 'fa-vk \r');
INSERT INTO `falists` VALUES ('426', 'fa-weibo \r');
INSERT INTO `falists` VALUES ('427', 'fa-renren \r');
INSERT INTO `falists` VALUES ('428', 'fa-pagelines \r');
INSERT INTO `falists` VALUES ('429', 'fa-stack-exchange \r');
INSERT INTO `falists` VALUES ('430', 'fa-arrow-circle-o-right \r');
INSERT INTO `falists` VALUES ('431', 'fa-arrow-circle-o-left \r');
INSERT INTO `falists` VALUES ('432', 'fa-toggle-left\r');
INSERT INTO `falists` VALUES ('433', 'fa-caret-square-o-left \r');
INSERT INTO `falists` VALUES ('434', 'fa-dot-circle-o \r');
INSERT INTO `falists` VALUES ('435', 'fa-wheelchair \r');
INSERT INTO `falists` VALUES ('436', 'fa-vimeo-square \r');
INSERT INTO `falists` VALUES ('437', 'fa-turkish-lira\r');
INSERT INTO `falists` VALUES ('438', 'fa-try \r');
INSERT INTO `falists` VALUES ('439', 'fa-plus-square-o \r');
INSERT INTO `falists` VALUES ('440', 'fa-space-shuttle \r');
INSERT INTO `falists` VALUES ('441', 'fa-slack \r');
INSERT INTO `falists` VALUES ('442', 'fa-envelope-square \r');
INSERT INTO `falists` VALUES ('443', 'fa-wordpress \r');
INSERT INTO `falists` VALUES ('444', 'fa-openid \r');
INSERT INTO `falists` VALUES ('445', 'fa-institution\r');
INSERT INTO `falists` VALUES ('446', 'fa-bank\r');
INSERT INTO `falists` VALUES ('447', 'fa-university \r');
INSERT INTO `falists` VALUES ('448', 'fa-mortar-board\r');
INSERT INTO `falists` VALUES ('449', 'fa-graduation-cap \r');
INSERT INTO `falists` VALUES ('450', 'fa-yahoo \r');
INSERT INTO `falists` VALUES ('451', 'fa-google \r');
INSERT INTO `falists` VALUES ('452', 'fa-reddit \r');
INSERT INTO `falists` VALUES ('453', 'fa-reddit-square \r');
INSERT INTO `falists` VALUES ('454', 'fa-stumbleupon-circle \r');
INSERT INTO `falists` VALUES ('455', 'fa-stumbleupon \r');
INSERT INTO `falists` VALUES ('456', 'fa-delicious \r');
INSERT INTO `falists` VALUES ('457', 'fa-digg \r');
INSERT INTO `falists` VALUES ('458', 'fa-pied-piper-square\r');
INSERT INTO `falists` VALUES ('459', 'fa-pied-piper \r');
INSERT INTO `falists` VALUES ('460', 'fa-pied-piper-alt \r');
INSERT INTO `falists` VALUES ('461', 'fa-drupal \r');
INSERT INTO `falists` VALUES ('462', 'fa-joomla \r');
INSERT INTO `falists` VALUES ('463', 'fa-language \r');
INSERT INTO `falists` VALUES ('464', 'fa-fax \r');
INSERT INTO `falists` VALUES ('465', 'fa-building \r');
INSERT INTO `falists` VALUES ('466', 'fa-child \r');
INSERT INTO `falists` VALUES ('467', 'fa-paw \r');
INSERT INTO `falists` VALUES ('468', 'fa-spoon \r');
INSERT INTO `falists` VALUES ('469', 'fa-cube \r');
INSERT INTO `falists` VALUES ('470', 'fa-cubes \r');
INSERT INTO `falists` VALUES ('471', 'fa-behance \r');
INSERT INTO `falists` VALUES ('472', 'fa-behance-square \r');
INSERT INTO `falists` VALUES ('473', 'fa-steam \r');
INSERT INTO `falists` VALUES ('474', 'fa-steam-square \r');
INSERT INTO `falists` VALUES ('475', 'fa-recycle \r');
INSERT INTO `falists` VALUES ('476', 'fa-automobile\r');
INSERT INTO `falists` VALUES ('477', 'fa-car \r');
INSERT INTO `falists` VALUES ('478', 'fa-cab\r');
INSERT INTO `falists` VALUES ('479', 'fa-taxi \r');
INSERT INTO `falists` VALUES ('480', 'fa-tree \r');
INSERT INTO `falists` VALUES ('481', 'fa-spotify \r');
INSERT INTO `falists` VALUES ('482', 'fa-deviantart \r');
INSERT INTO `falists` VALUES ('483', 'fa-soundcloud \r');
INSERT INTO `falists` VALUES ('484', 'fa-database \r');
INSERT INTO `falists` VALUES ('485', 'fa-file-pdf-o \r');
INSERT INTO `falists` VALUES ('486', 'fa-file-word-o \r');
INSERT INTO `falists` VALUES ('487', 'fa-file-excel-o \r');
INSERT INTO `falists` VALUES ('488', 'fa-file-powerpoint-o \r');
INSERT INTO `falists` VALUES ('489', 'fa-file-photo-o\r');
INSERT INTO `falists` VALUES ('490', 'fa-file-picture-o\r');
INSERT INTO `falists` VALUES ('491', 'fa-file-image-o \r');
INSERT INTO `falists` VALUES ('492', 'fa-file-zip-o\r');
INSERT INTO `falists` VALUES ('493', 'fa-file-archive-o \r');
INSERT INTO `falists` VALUES ('494', 'fa-file-sound-o\r');
INSERT INTO `falists` VALUES ('495', 'fa-file-audio-o \r');
INSERT INTO `falists` VALUES ('496', 'fa-file-movie-o\r');
INSERT INTO `falists` VALUES ('497', 'fa-file-video-o \r');
INSERT INTO `falists` VALUES ('498', 'fa-file-code-o \r');
INSERT INTO `falists` VALUES ('499', 'fa-vine \r');
INSERT INTO `falists` VALUES ('500', 'fa-codepen \r');
INSERT INTO `falists` VALUES ('501', 'fa-jsfiddle \r');
INSERT INTO `falists` VALUES ('502', 'fa-life-bouy\r');
INSERT INTO `falists` VALUES ('503', 'fa-life-saver\r');
INSERT INTO `falists` VALUES ('504', 'fa-support\r');
INSERT INTO `falists` VALUES ('505', 'fa-life-ring \r');
INSERT INTO `falists` VALUES ('506', 'fa-circle-o-notch \r');
INSERT INTO `falists` VALUES ('507', 'fa-ra\r');
INSERT INTO `falists` VALUES ('508', 'fa-rebel \r');
INSERT INTO `falists` VALUES ('509', 'fa-ge\r');
INSERT INTO `falists` VALUES ('510', 'fa-empire \r');
INSERT INTO `falists` VALUES ('511', 'fa-git-square \r');
INSERT INTO `falists` VALUES ('512', 'fa-git \r');
INSERT INTO `falists` VALUES ('513', 'fa-hacker-news \r');
INSERT INTO `falists` VALUES ('514', 'fa-tencent-weibo \r');
INSERT INTO `falists` VALUES ('515', 'fa-qq \r');
INSERT INTO `falists` VALUES ('516', 'fa-wechat\r');
INSERT INTO `falists` VALUES ('517', 'fa-weixin \r');
INSERT INTO `falists` VALUES ('518', 'fa-send\r');
INSERT INTO `falists` VALUES ('519', 'fa-paper-plane \r');
INSERT INTO `falists` VALUES ('520', 'fa-send-o\r');
INSERT INTO `falists` VALUES ('521', 'fa-paper-plane-o \r');
INSERT INTO `falists` VALUES ('522', 'fa-history \r');
INSERT INTO `falists` VALUES ('523', 'fa-circle-thin \r');
INSERT INTO `falists` VALUES ('524', 'fa-header \r');
INSERT INTO `falists` VALUES ('525', 'fa-paragraph \r');
INSERT INTO `falists` VALUES ('526', 'fa-sliders \r');
INSERT INTO `falists` VALUES ('527', 'fa-share-alt \r');
INSERT INTO `falists` VALUES ('528', 'fa-share-alt-square \r');
INSERT INTO `falists` VALUES ('529', 'fa-bomb ');
